# Generated by Django 5.0.6 on 2024-06-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='project.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.class'),
        ),
    ]
